### ISSUE TITLE
Led Cutout

### ISSUE THREAD

**Issue by trentsmart** [JMiahMan1/Home-Assistant-Smart-Speaker#1]
Just maybe a suggestion, maybe not though. With the little led strip that I got the little mounting holes were on the bottom and not the top lol so i had to flip the strip over and it made the DIN side on the other side so I tried as best I could to make the same rectangle hole as you did on the left, on the right this time. Great work btw.

**Comment by JMiahMan1** [comment]
I know there are different configurations and even the spacing of the holes can be different from order to order so I have just removed the posts altogether and used a little bit of hot glue to keep it in place. I might create a tab on one end and then snug it just underneath the speaker, we'll see how it works. I warned everyone it was a work in progress lol. Thanks for the feedback though.

**Comment by JMiahMan1** [comment]
I think with removing the posts this has been fixed, unless I misunderstood, so I am going to close this out. Thanks again for your feedback!
